// modules-sst.js — NCR Solutions Quiz SST
// ============================================================
//   BANQUE DE QUESTIONS PAR MODULE THÉMATIQUE (Mode Examinateur)
// ============================================================
// Chaque module = un déroulé pédagogique SST indépendant.
// Catégories utilisées (objectif n°2) :
//   reconnaissance | gravite | conduite | erreurs | situation | pratique
// Difficulté : facile | moyen | difficile
//
// Pour ajouter un nouveau module plus tard (objectif n°2/8) :
//   1) Ajouter un objet { key, name, icon, questions:[...] } dans SST_THEMES
//   2) Chaque question : { q, a:[...4 réponses...], c:index réponse correcte, e:explication, cat, diff }
// Aucune autre partie du code n'a besoin d'être modifiée : le tableau de
// bord pédagogique et le moteur de quiz lisent dynamiquement ce tableau.

window.SST_THEMES = [
  {
    key: "protection",
    name: "La protection",
    icon: "🛡️",
    questions: [
      { q: "Quelle est la 1ère étape de la protection ?", a: ["Supprimer le danger", "S'exposer au danger", "Alerter directement", "Examiner la victime"], c: 0, e: "Supprimer la source du danger est la mesure de protection la plus efficace.", cat: "conduite", diff: "facile" },
      { q: "Si le danger ne peut pas être supprimé, que fait-on ?", a: ["On isole la zone", "On reste juste à côté", "On l'ignore", "On porte la victime"], c: 0, e: "On isole la zone pour éviter qu'une autre personne ne soit blessée.", cat: "conduite", diff: "facile" },
      { q: "Face à un câble électrique au sol, que faire ?", a: ["L'écarter à la main", "Baliser largement la zone", "Couper le compteur soi-même", "Tirer la victime vers soi"], c: 1, e: "On balise largement car l'électricité peut se propager au sol sur plusieurs mètres.", cat: "conduite", diff: "moyen" },
      { q: "Qu'est-ce qu'un dégagement d'urgence ?", a: ["Déplacer systématiquement toute victime", "Déplacer la victime uniquement en cas de danger vital immédiat et incontrôlable", "Mettre la victime à l'ombre", "Une procédure obligatoire pour tout accident"], c: 1, e: "Le dégagement d'urgence est l'exception : uniquement si rester sur place expose la victime à une mort certaine.", cat: "gravite", diff: "moyen" },
      { q: "Lors d'un dégagement d'urgence, quelle est la priorité absolue ?", a: ["Aller le plus vite possible", "La sécurité du sauveteur lui-même", "Prendre son matériel avant", "Ne pas faire mal à la victime"], c: 1, e: "Si le sauveteur devient lui-même victime, il ne peut plus porter secours à personne.", cat: "conduite", diff: "facile" },
      { q: "Sur la route, après un accident, le SST doit d'abord :", a: ["Signaler l'accident (gilet, triangle, feux de détresse)", "Foncer vers la victime", "Appeler immédiatement la famille", "Déplacer le véhicule accidenté"], c: 0, e: "Se rendre visible et signaler le danger évite un sur-accident, première cause de blessures supplémentaires sur route.", cat: "situation", diff: "moyen" },
      { q: "Dans un local enfumé, le SST doit :", a: ["Entrer en retenant sa respiration", "Ne jamais entrer sans équipement adapté", "Entrer avec un linge humide sur le visage", "Allumer la lumière pour mieux voir"], c: 1, e: "Les fumées d'incendie sont extrêmement toxiques : on ne s'y expose jamais sans équipement de protection respiratoire.", cat: "erreurs", diff: "moyen" },
      { q: "Face à une machine qui a happé un vêtement, le geste prioritaire est :", a: ["Actionner l'arrêt d'urgence", "Tirer sur le vêtement", "Crier pour prévenir", "Verser de l'eau sur la machine"], c: 0, e: "L'arrêt d'urgence coupe l'énergie de la machine : c'est le geste prioritaire pour stopper le danger.", cat: "conduite", diff: "facile" },
      { q: "En cas de fuite de gaz, la bonne conduite est :", a: ["Allumer la lumière pour vérifier", "Ouvrir les fenêtres pour ventiler, sans actionner d'interrupteur", "Téléphoner depuis la pièce concernée", "Allumer une bougie pour repérer l'odeur"], c: 1, e: "Toute étincelle (interrupteur, sonnette, téléphone) peut provoquer une explosion : on ventile sans créer d'étincelle.", cat: "erreurs", diff: "moyen" },
      { q: "La règle d'or de la protection est :", a: ["Aller le plus vite possible", "Ne jamais faire de nouvelle victime", "Toujours poser un garrot", "Attendre les secours sans agir"], c: 1, e: "Le but premier de la protection est d'éviter tout sur-accident : zéro victime supplémentaire.", cat: "reconnaissance", diff: "facile" },
      { q: "Mise en situation : un collègue est tombé dans une fosse de visite automobile sans ventilation. Que faire ?", a: ["Descendre immédiatement le secourir", "Ne jamais descendre sans s'assurer que l'atmosphère est respirable, alerter et baliser", "Lui jeter une corde et attendre", "Ouvrir toutes les portes du garage seulement"], c: 1, e: "Une atmosphère confinée peut être irrespirable : un SST qui descend sans précaution devient une 2ᵉ victime.", cat: "pratique", diff: "difficile" },
      { q: "Une victime consciente peut-elle participer à sa propre protection ?", a: ["Non, jamais", "Oui, si elle est consciente et capable de se déplacer seule vers une zone sûre", "Seulement si elle marche déjà", "C'est interdit par la réglementation"], c: 1, e: "Si la victime peut bouger seule sans risque supplémentaire, on l'encourage à rejoindre une zone sûre.", cat: "conduite", diff: "moyen" }
    ]
  },
  {
    key: "alerte",
    name: "L'alerte",
    icon: "📞",
    questions: [
      { q: "Quel numéro permet de contacter le SAMU en France ?", a: ["15", "17", "18", "112"], c: 0, e: "Le 15 est le numéro dédié à l'aide médicale urgente en France, géré par le SAMU.", cat: "reconnaissance", diff: "facile" },
      { q: "Quel numéro d'urgence est valable dans toute l'Union européenne ?", a: ["15", "17", "18", "112"], c: 3, e: "Le 112 est le numéro d'appel d'urgence unique européen.", cat: "reconnaissance", diff: "facile" },
      { q: "Quelle information doit être donnée en priorité lors d'un message d'alerte ?", a: ["Le nom de la victime", "Le lieu précis de l'accident", "L'âge de la victime", "L'heure exacte"], c: 1, e: "Donner immédiatement le lieu précis permet aux secours de se diriger sans délai.", cat: "conduite", diff: "facile" },
      { q: "Après avoir transmis les informations à l'opérateur, l'appelant doit :", a: ["Raccrocher immédiatement", "Rester en ligne jusqu'à ce que le régulateur mette fin à l'appel", "Quitter les lieux", "Proposer un café à la victime"], c: 1, e: "Le régulateur peut avoir besoin de précisions ou donner des consignes : c'est lui qui termine l'appel.", cat: "conduite", diff: "moyen" },
      { q: "Le nombre de victimes est-il utile à transmettre lors de l'alerte ?", a: ["Oui, cela conditionne les moyens envoyés", "Non, jamais demandé", "Seulement au-delà de 5 victimes", "Seulement si le régulateur insiste"], c: 0, e: "Le nombre de victimes permet de dimensionner correctement les secours envoyés.", cat: "conduite", diff: "facile" },
      { q: "Seul face à une victime en arrêt cardiaque, que fait-on en priorité ?", a: ["Masser puis alerter ensuite", "Alerter d'abord (en haut-parleur si possible), puis débuter le massage", "Aller chercher un DAE à 1 km sans masser", "Attendre qu'un témoin passe"], c: 1, e: "Seul, on alerte en premier (idéalement en mode mains libres) avant de débuter la réanimation.", cat: "erreurs", diff: "moyen" },
      { q: "Que faire si la communication est coupée pendant l'appel aux secours ?", a: ["Abandonner, l'essentiel est dit", "Rappeler immédiatement le même numéro", "Changer de téléphone sans rappeler", "Attendre que les secours rappellent"], c: 1, e: "On rappelle sans tarder pour s'assurer que toutes les informations ont bien été transmises.", cat: "erreurs", diff: "moyen" },
      { q: "Peut-on déléguer l'alerte à un témoin ?", a: ["Non, jamais", "Oui, à condition de lui donner des consignes claires et précises", "Uniquement si la victime le demande", "Uniquement si le témoin insiste"], c: 1, e: "Si le SST doit rester auprès de la victime, il peut déléguer l'alerte à un témoin en lui donnant des instructions précises.", cat: "conduite", diff: "moyen" },
      { q: "Quel équipement demander en priorité à un témoin face à un arrêt cardiaque ?", a: ["Un défibrillateur automatisé externe (DAE)", "Un verre d'eau", "Une civière", "Un médecin du quartier"], c: 0, e: "Chaque minute sans défibrillation réduit fortement les chances de survie.", cat: "reconnaissance", diff: "facile" },
      { q: "Quelles qualités doit avoir un message d'alerte efficace ?", a: ["Vague et général", "Clair et précis (lieu, nature, victimes, gestes déjà faits)", "Le plus long possible", "Crié fort"], c: 1, e: "Un message d'alerte efficace est structuré : lieu, nature de l'événement, état de la victime, gestes déjà entrepris.", cat: "conduite", diff: "facile" },
      { q: "Mise en situation : dans l'entreprise, un collègue se blesse gravement à la main avec une machine. Vous êtes seul. Quel est l'ordre des actions ?", a: ["Alerter, puis protéger, puis examiner", "Protéger, examiner, agir sur l'urgence vitale, puis alerter ou faire alerter", "Examiner uniquement, sans alerter", "Attendre l'arrivée spontanée des secours"], c: 1, e: "On protège, on examine, on traite l'urgence vitale immédiate, et on alerte (soi-même ou via un témoin) le plus tôt possible.", cat: "pratique", diff: "difficile" },
      { q: "À quel service correspond le numéro 18 ?", a: ["Le SAMU", "La police", "Les sapeurs-pompiers", "Les secours en mer"], c: 2, e: "Le 18 permet de joindre les sapeurs-pompiers.", cat: "reconnaissance", diff: "facile" }
    ]
  },
  {
    key: "hemorragie",
    name: "L'hémorragie",
    icon: "🩸",
    questions: [
      { q: "Face à une hémorragie externe, quel est le geste prioritaire ?", a: ["Comprimer directement la plaie", "Laver abondamment la plaie", "Poser systématiquement un garrot", "Donner un comprimé contre la douleur"], c: 0, e: "La compression manuelle directe est le geste de premier choix pour arrêter une hémorragie.", cat: "conduite", diff: "facile" },
      { q: "Comment reconnaît-on une hémorragie externe grave ?", a: ["Le sang coule lentement et s'arrête vite", "Le saignement est abondant et ne s'arrête pas spontanément", "La plaie est petite mais rouge", "La victime ne ressent rien"], c: 1, e: "Une hémorragie est grave lorsque le saignement est abondant, continu, et ne cesse pas spontanément.", cat: "reconnaissance", diff: "facile" },
      { q: "Quels sont des signes de gravité (état de choc) chez une victime qui saigne beaucoup ?", a: ["Pâleur, sueurs, pouls rapide et faible", "Rougeur du visage et calme apparent", "Augmentation de la force musculaire", "Aucun signe particulier"], c: 0, e: "Pâleur, sueurs froides, pouls rapide et filant traduisent un état de choc hémorragique : urgence vitale.", cat: "gravite", diff: "moyen" },
      { q: "La compression directe ne suffit pas à arrêter le saignement. Que faire ensuite ?", a: ["Poser un garrot en dernier recours et noter l'heure de pose", "Laisser la victime saigner en attendant les secours", "Mettre simplement un pansement sans rien d'autre", "Ne rien faire de plus"], c: 0, e: "Le garrot est utilisé en dernier recours, lorsque la compression est inefficace ou impossible. Noter l'heure de pose est crucial pour l'équipe médicale.", cat: "conduite", diff: "moyen" },
      { q: "Peut-on desserrer un garrot une fois posé ?", a: ["Oui, dès que le saignement diminue", "Non, jamais, sauf avis médical contraire", "Oui, toutes les 10 minutes", "Oui, si la victime le demande"], c: 1, e: "Une fois posé, un garrot ne doit jamais être desserré : cela pourrait relâcher une hémorragie massive.", cat: "erreurs", diff: "difficile" },
      { q: "Une hémorragie du nez (épistaxis) simple : que faire ?", a: ["Pencher la tête en arrière et comprimer la narine", "Pencher la tête en avant et comprimer la narine", "Allonger la victime sur le dos", "Faire moucher fort la victime"], c: 1, e: "On penche la tête légèrement en avant pour éviter d'avaler le sang, et on comprime la narine.", cat: "pratique", diff: "moyen" },
      { q: "Une victime présente une hémorragie ET ne respire plus. Que traite-t-on en premier ?", a: ["La respiration, car plus grave", "L'hémorragie, car le sang qui s'écoule doit être stoppé sans délai, avant de traiter l'absence de respiration", "Les deux en même temps seul", "Aucune, on attend les secours"], c: 1, e: "Une hémorragie massive non contrôlée peut entraîner le décès en quelques minutes : elle est traitée sans délai.", cat: "situation", diff: "difficile" },
      { q: "Une plaie de l'abdomen avec un objet planté dedans : que fait-on ?", a: ["Retirer l'objet immédiatement", "Ne jamais retirer l'objet, le maintenir en place", "Pousser l'objet plus profondément", "Tourner l'objet pour le desserrer"], c: 1, e: "Retirer un objet empalé peut aggraver l'hémorragie : on le laisse en place et on cale autour.", cat: "erreurs", diff: "difficile" },
      { q: "Erreur fréquente face à une hémorragie : laver la plaie avant de comprimer.", a: ["C'est la bonne méthode", "C'est une erreur : on comprime d'abord, sans perdre de temps à nettoyer", "Cela n'a aucune importance", "Il faut désinfecter à l'alcool d'abord"], c: 1, e: "Devant une hémorragie abondante, on comprime immédiatement : nettoyer la plaie n'est pas la priorité.", cat: "erreurs", diff: "moyen" },
      { q: "Quelle position privilégier pour une victime consciente présentant une plaie au ventre ?", a: ["Allongée, jambes fléchies (genoux relevés)", "Position latérale de sécurité", "Assise normalement", "Debout"], c: 0, e: "Jambes fléchies : cela détend la paroi abdominale et limite la douleur.", cat: "pratique", diff: "moyen" }
    ]
  },
  {
    key: "plaies",
    name: "Les plaies",
    icon: "🩹",
    questions: [
      { q: "Comment traiter une plaie simple (peu profonde, qui ne saigne pas abondamment) ?", a: ["La nettoyer à l'eau et au savon", "Y verser de l'alcool", "La recouvrir de terre", "Ne rien faire"], c: 0, e: "Un nettoyage à l'eau claire et au savon suffit avant de recouvrir d'un pansement propre.", cat: "conduite", diff: "facile" },
      { q: "Quels signes définissent une plaie grave ?", a: ["Petite coupure superficielle", "Plaie qui saigne abondamment, profonde, étendue, ou touchant le thorax/l'abdomen/le visage", "Une simple égratignure", "Une plaie qui ne fait pas mal"], c: 1, e: "Une plaie grave se reconnaît par sa profondeur, son étendue, son siège (thorax, abdomen, visage, œil) ou un saignement abondant.", cat: "reconnaissance", diff: "facile" },
      { q: "Un doigt a été sectionné lors d'un accident. Comment conserver le fragment ?", a: ["Le jeter, il est inutilisable", "Le placer dans un sac propre, posé sur un lit de glace, sans contact direct", "Le mettre directement sur la glace", "Tenter de le recoudre soi-même"], c: 1, e: "Le fragment dans un sac propre, sur de la glace sans contact direct, préserve les chances de réimplantation.", cat: "pratique", diff: "moyen" },
      { q: "Quelle position privilégier pour une plaie au thorax ?", a: ["Position semi-assise, qui facilite la respiration", "Position latérale de sécurité", "À plat ventre", "Debout contre un mur"], c: 0, e: "La position semi-assise facilite l'effort respiratoire en cas de plaie thoracique.", cat: "conduite", diff: "moyen" },
      { q: "Faut-il retirer un corps étranger planté dans une plaie ?", a: ["Oui, toujours", "Non, jamais, sauf indication contraire des secours", "Seulement s'il est petit", "Seulement si la victime insiste"], c: 1, e: "Retirer un corps étranger peut relancer ou aggraver une hémorragie : on le laisse en place.", cat: "erreurs", diff: "moyen" },
      { q: "Une plaie à l'œil : que faire ?", a: ["Rincer abondamment et frotter", "Ne jamais frotter, ne pas tenter de retirer un corps étranger visible, couvrir légèrement et alerter", "Mettre des gouttes quelconques", "Faire cligner rapidement l'œil"], c: 1, e: "L'œil est très fragile : on ne frotte jamais, on ne retire rien, on protège légèrement en attendant un avis médical.", cat: "situation", diff: "difficile" },
      { q: "Une morsure d'animal est-elle considérée comme une plaie grave ?", a: ["Non, jamais", "Oui, en raison du risque infectieux et de la nécessité d'un avis médical", "Seulement si elle saigne beaucoup", "Seulement pour les morsures de chien"], c: 1, e: "Toute morsure (risque infectieux, rage potentielle) doit être considérée avec sérieux et faire l'objet d'un avis médical.", cat: "gravite", diff: "moyen" },
      { q: "Erreur fréquente : appliquer du désinfectant coloré sur une plaie qui devra être examinée par un médecin.", a: ["Bonne pratique", "Erreur : cela peut masquer l'aspect de la plaie pour l'examen médical", "Obligatoire dans tous les cas", "Cela accélère la guérison"], c: 1, e: "Un désinfectant coloré peut gêner l'évaluation médicale ultérieure de la plaie.", cat: "erreurs", diff: "difficile" },
      { q: "Mise en situation : un salarié se coupe avec un objet rouillé en extérieur. Plaie peu profonde. Que faire après le nettoyage ?", a: ["Ne rien faire de plus", "Recommander une vérification du statut vaccinal antitétanique", "Mettre du sucre sur la plaie", "Frotter fort la plaie"], c: 1, e: "Le risque tétanique existe avec les objets souillés/rouillés : on recommande de vérifier la vaccination.", cat: "pratique", diff: "difficile" },
      { q: "Quel est le bon ordre des gestes face à une plaie simple ?", a: ["Couvrir, puis nettoyer", "Se laver les mains, nettoyer la plaie, puis couvrir avec un pansement propre", "Désinfecter à l'alcool puis frotter", "Appliquer une crème puis laver"], c: 1, e: "On se lave les mains, on nettoie à l'eau et au savon, puis on protège avec un pansement propre.", cat: "conduite", diff: "facile" }
    ]
  },
  {
    key: "brulures",
    name: "Les brûlures",
    icon: "🔥",
    questions: [
      { q: "Quel est le geste de premier secours face à une brûlure thermique ?", a: ["Appliquer du beurre", "Refroidir immédiatement à l'eau tempérée pendant environ 10 minutes", "Percer les cloques", "Appliquer de la glace directement"], c: 1, e: "Refroidissement à l'eau tempérée (15-25°C) pendant environ 10 minutes. Beurre et glace directe sont à proscrire.", cat: "conduite", diff: "facile" },
      { q: "Comment reconnaît-on une brûlure grave ?", a: ["Rougeur simple de la peau, comme un coup de soleil", "Cloques étendues, peau blanche/noire/carbonisée, ou brûlure au visage/mains/articulations/zones étendues", "Toute brûlure qui pique un peu", "Une brûlure qui ne fait pas mal du tout n'est jamais grave"], c: 1, e: "Une brûlure profonde, étendue, ou touchant le visage, les mains, les voies respiratoires ou les articulations, est grave.", cat: "reconnaissance", diff: "facile" },
      { q: "Une brûlure qui ne fait pas mal est-elle moins grave ?", a: ["Oui, l'absence de douleur signifie qu'elle est superficielle", "Non, l'absence de douleur peut au contraire signaler une brûlure profonde ayant détruit les terminaisons nerveuses", "Cela dépend de la couleur", "Oui, toujours"], c: 1, e: "Une brûlure profonde peut détruire les nerfs et donc ne plus faire mal : c'est un signe de gravité, pas de soulagement.", cat: "gravite", diff: "difficile" },
      { q: "Faut-il percer les cloques d'une brûlure ?", a: ["Oui, pour évacuer le liquide", "Non, jamais : la cloque protège la zone d'une infection", "Seulement si elle est petite", "Seulement avec une aiguille stérile"], c: 1, e: "La cloque (phlyctène) est une protection naturelle ; la percer expose à un risque d'infection.", cat: "erreurs", diff: "moyen" },
      { q: "Faut-il retirer les vêtements collés à une brûlure ?", a: ["Oui, systématiquement et rapidement", "Non, on ne retire jamais un vêtement qui adhère à la peau brûlée", "Seulement s'ils sont en coton", "Oui, en tirant fort"], c: 1, e: "Un vêtement collé à la peau brûlée ne doit jamais être arraché : on découpe autour sans toucher la zone adhérente.", cat: "erreurs", diff: "moyen" },
      { q: "Brûlure chimique (produit sur la peau) : que faire en priorité ?", a: ["Rincer abondamment à l'eau claire le plus longtemps possible", "Neutraliser avec un autre produit chimique", "Frotter pour enlever le produit", "Appliquer une crème immédiatement"], c: 0, e: "Le rinçage abondant et prolongé à l'eau claire élimine le produit en cause ; ne jamais tenter de neutraliser chimiquement.", cat: "situation", diff: "moyen" },
      { q: "Brûlure électrique (après électrisation) : particularité à connaître ?", a: ["Elle ne touche que la surface de la peau", "Elle peut être beaucoup plus étendue en profondeur que ce qui est visible à la surface", "Elle ne nécessite jamais d'avis médical", "Elle se traite comme une simple coupure"], c: 1, e: "Une brûlure électrique peut détruire des tissus profonds invisibles à l'œil : un avis médical est systématique.", cat: "gravite", diff: "difficile" },
      { q: "Mise en situation : un enfant renverse une casserole d'eau chaude sur son bras. Que faites-vous en premier ?", a: ["L'emmener directement aux urgences sans rien faire avant", "Refroidir immédiatement le bras à l'eau tempérée pendant 10 à 20 minutes, puis alerter si besoin", "Appliquer de la pommade tout de suite", "Frotter le bras avec un linge sec"], c: 1, e: "Le refroidissement immédiat limite la profondeur de la brûlure ; on alerte ensuite si la brûlure est étendue ou grave.", cat: "pratique", diff: "moyen" },
      { q: "Quelle est la durée recommandée du refroidissement d'une brûlure thermique ?", a: ["2-3 minutes", "Environ 10 à 20 minutes", "1 heure", "Aucune durée précise"], c: 1, e: "On refroidit à l'eau tempérée pendant 10 à 20 minutes selon les recommandations actuelles.", cat: "conduite", diff: "facile" },
      { q: "Erreur fréquente face à une brûlure : appliquer de la glace directement sur la peau.", a: ["Bonne pratique pour calmer la douleur", "Erreur : la glace directe peut aggraver la lésion (gelure superposée)", "Recommandé systématiquement", "Sans effet"], c: 1, e: "La glace directe peut créer une lésion supplémentaire par le froid : on utilise de l'eau tempérée, jamais de la glace au contact direct.", cat: "erreurs", diff: "moyen" }
    ]
  },
  {
    key: "etouffement",
    name: "L'étouffement",
    icon: "🫁",
    questions: [
      { q: "Quel est le signe caractéristique d'un étouffement total ?", a: ["La victime tousse fort", "La victime parle difficilement mais s'exprime", "La victime ne peut ni parler, ni tousser, ni respirer, et porte souvent les mains à sa gorge", "La victime pleure abondamment"], c: 2, e: "Dans l'obstruction totale, l'air ne passe plus du tout : c'est une urgence absolue.", cat: "reconnaissance", diff: "facile" },
      { q: "Comment reconnaît-on un étouffement partiel ?", a: ["La victime ne peut plus du tout parler", "La victime tousse, peut encore parler ou émettre des sons", "La victime est totalement silencieuse", "La victime perd connaissance immédiatement"], c: 1, e: "Dans l'obstruction partielle, l'air passe encore en partie : la victime tousse et peut s'exprimer.", cat: "reconnaissance", diff: "facile" },
      { q: "Que faire face à un étouffement partiel (la victime tousse encore) ?", a: ["Taper immédiatement dans le dos très fort", "La laisser tousser, l'encourager, ne pas intervenir physiquement sauf aggravation", "Faire la méthode de Heimlich tout de suite", "Lui faire boire de l'eau"], c: 1, e: "Tant que la toux est efficace, on laisse la victime tousser : c'est le meilleur moyen naturel d'expulser le corps étranger.", cat: "conduite", diff: "moyen" },
      { q: "Quelle est la technique face à un étouffement total chez l'adulte conscient ?", a: ["5 claques dans le dos, puis si échec 5 compressions abdominales (Heimlich), en alternance", "Lui faire boire de l'eau rapidement", "L'allonger immédiatement au sol", "Ne rien faire et attendre"], c: 0, e: "On réalise jusqu'à 5 claques vigoureuses entre les omoplates, puis si besoin 5 compressions abdominales, en alternant.", cat: "conduite", diff: "facile" },
      { q: "La méthode de Heimlich est-elle adaptée au nourrisson (moins d'1 an) ?", a: ["Oui, exactement de la même façon", "Non : on utilise des claques dans le dos et des compressions thoraciques (pas abdominales)", "Oui, mais en position assise", "Non, on ne fait jamais rien chez le nourrisson"], c: 1, e: "Chez le nourrisson, les compressions abdominales sont proscrites (risque de lésion des organes) : on utilise claques dorsales et compressions thoraciques.", cat: "erreurs", diff: "difficile" },
      { q: "Une victime d'étouffement total devient inconsciente. Que faire ?", a: ["Continuer uniquement les claques dans le dos", "L'allonger au sol, alerter immédiatement et débuter une réanimation cardio-pulmonaire", "Lui donner de l'eau", "Attendre qu'elle se réveille seule"], c: 1, e: "En cas de perte de connaissance, on alerte et on débute le massage cardiaque : chaque compression peut aussi aider à mobiliser le corps étranger.", cat: "gravite", diff: "difficile" },
      { q: "Faut-il faire boire la victime qui s'étouffe pour 'faire passer' le corps étranger ?", a: ["Oui, c'est efficace", "Non, jamais : cela peut aggraver l'obstruction", "Seulement de l'eau tiède", "Seulement si elle le demande"], c: 1, e: "Faire boire une personne qui s'étouffe est inefficace et dangereux : cela peut aggraver l'obstruction des voies aériennes.", cat: "erreurs", diff: "moyen" },
      { q: "Mise en situation : lors d'un repas d'entreprise, un collègue porte les mains à sa gorge, ne tousse plus et ne peut plus parler. Que faites-vous ?", a: ["Lui demander de se calmer et d'attendre", "Réaliser sans délai les claques dans le dos puis la méthode de Heimlich si besoin", "Appeler les secours et ne rien faire d'autre en l'attendant", "Lui taper doucement sur l'épaule"], c: 1, e: "Face à une obstruction totale confirmée, on agit immédiatement par les claques dans le dos puis Heimlich, sans attendre les secours.", cat: "pratique", diff: "moyen" },
      { q: "Après une désobstruction réussie (le corps étranger est expulsé), que faire ?", a: ["Considérer que tout est terminé, sans suite particulière", "Recommander malgré tout un avis médical, surtout après des compressions abdominales", "Refaire systématiquement la manœuvre par sécurité", "Donner immédiatement à boire"], c: 1, e: "Même après réussite, un avis médical est recommandé (risque de lésion interne lié aux compressions, ou fragment résiduel).", cat: "conduite", diff: "difficile" }
    ]
  },
  {
    key: "traumatismes",
    name: "Les traumatismes",
    icon: "🦴",
    questions: [
      { q: "Vous suspectez un traumatisme du dos ou de la colonne vertébrale chez une victime consciente. Que faire ?", a: ["La faire marcher pour vérifier", "Maintenir la tête et éviter tout mouvement du dos et du cou", "La tirer pour la dégager rapidement", "L'asseoir pour la rassurer"], c: 1, e: "Tout mouvement peut aggraver une lésion de la moelle épinière : on maintient la tête en attendant les secours.", cat: "conduite", diff: "facile" },
      { q: "Comment reconnaître un traumatisme de membre potentiellement grave ?", a: ["Douleur légère qui passe vite", "Déformation visible, douleur vive, impossibilité de bouger ou de prendre appui", "Aucun signe particulier", "Une simple rougeur"], c: 1, e: "Déformation, douleur intense, impotence fonctionnelle sont les signes évocateurs d'une fracture ou entorse grave.", cat: "reconnaissance", diff: "facile" },
      { q: "Faut-il tenter de remettre en place un membre déformé après un traumatisme ?", a: ["Oui, immédiatement", "Non, jamais : on immobilise dans la position trouvée", "Seulement si la victime le demande", "Oui, en tirant fermement"], c: 1, e: "On ne réduit jamais une fracture ou une luxation soi-même : on immobilise dans la position où le membre se trouve.", cat: "erreurs", diff: "moyen" },
      { q: "Une victime se plaint d'une douleur au cou après une chute. Que faire en priorité ?", a: ["Lui demander de bouger la tête pour vérifier", "Maintenir sa tête immobile avec les mains, sans la mobiliser", "L'asseoir directement", "Lui mettre un coussin sous la tête"], c: 1, e: "Toute suspicion de traumatisme du rachis cervical impose une immobilisation manuelle de la tête, sans la bouger.", cat: "situation", diff: "moyen" },
      { q: "Une personne vient d'être dégagée d'un contact électrique. Faut-il l'examiner même si elle semble bien ?", a: ["Non, si elle semble bien il n'y a rien à faire", "Oui, l'examiner systématiquement : des lésions internes peuvent être invisibles", "Lui donner à boire immédiatement", "Attendre qu'elle se relève seule"], c: 1, e: "Une électrisation peut provoquer des troubles du rythme cardiaque ou des brûlures profondes invisibles : examen systématique.", cat: "gravite", diff: "moyen" },
      { q: "Un traumatisme crânien avec perte de connaissance brève : faut-il s'en inquiéter même si la victime semble aller bien ensuite ?", a: ["Non, si elle est réveillée tout va bien", "Oui, toute perte de connaissance après un choc à la tête impose un avis médical et une surveillance", "Seulement si elle a un hématome visible", "Non, sauf si elle vomit"], c: 1, e: "Toute perte de connaissance après un traumatisme crânien, même brève, nécessite un avis médical : risque d'hématome retardé.", cat: "gravite", diff: "difficile" },
      { q: "Erreur fréquente : asseoir une victime suspectée de traumatisme du dos pour 'la mettre plus à l'aise'.", a: ["Bonne pratique", "Erreur : cela peut aggraver une lésion de la colonne vertébrale", "Recommandé systématiquement", "Sans conséquence"], c: 1, e: "On ne mobilise jamais une victime suspectée de traumatisme vertébral, même pour la 'mettre à l'aise'.", cat: "erreurs", diff: "moyen" },
      { q: "Mise en situation : un ouvrier chute d'une échelle de 2 mètres et se plaint du dos, conscient. Que faites-vous ?", a: ["Le relever pour vérifier qu'il tient debout", "Le maintenir immobile, ne pas le déplacer, alerter les secours en précisant le mécanisme de chute", "Le faire asseoir contre le mur", "Le laisser seul en attendant"], c: 1, e: "Mécanisme de chute évocateur de traumatisme rachidien : immobilisation stricte et alerte précisant les circonstances.", cat: "pratique", diff: "difficile" },
      { q: "Une entorse de la cheville simple : que peut-on faire en attendant un avis médical ?", a: ["Faire marcher la victime normalement", "Mettre au repos, surélever si possible, ne pas faire d'appui forcé", "Masser fortement la zone", "Appliquer de la chaleur immédiatement"], c: 1, e: "Repos et surélévation limitent l'œdème ; on évite tout appui forcé en attendant un avis médical.", cat: "pratique", diff: "moyen" }
    ]
  },
  {
    key: "perte_connaissance",
    name: "La perte de connaissance",
    icon: "😴",
    questions: [
      { q: "Comment vérifier l'état de conscience d'une victime ?", a: ["En la secouant fermement", "En lui parlant, en lui posant une question simple et en lui demandant un geste précis", "En lui pinçant la peau", "En l'aspergeant d'eau froide"], c: 1, e: "On s'adresse calmement à la victime en lui demandant une réponse verbale et un geste simple.", cat: "reconnaissance", diff: "facile" },
      { q: "Une victime est inconsciente mais respire normalement. Quel est son état ?", a: ["Elle est en arrêt cardiaque", "Elle est dans un état comateux : inconsciente mais la respiration est conservée", "Elle dort profondément", "Elle simule"], c: 1, e: "L'inconscience avec respiration conservée correspond à un état comateux : il faut la mettre en PLS et surveiller.", cat: "reconnaissance", diff: "moyen" },
      { q: "Dans quelle position doit être placée une victime inconsciente qui respire ?", a: ["Assise contre un mur", "En position latérale de sécurité (PLS)", "Allongée sur le dos", "Debout, soutenue"], c: 1, e: "La PLS maintient les voies aériennes dégagées et prévient l'inhalation de vomissements.", cat: "conduite", diff: "facile" },
      { q: "Pourquoi place-t-on une victime inconsciente qui respire en PLS ?", a: ["Pour qu'elle dorme plus confortablement", "Pour maintenir ses voies aériennes libres et prévenir l'inhalation de vomissements", "Pour la réchauffer", "Pour soulager son dos"], c: 1, e: "La PLS favorise l'écoulement des liquides vers l'extérieur et empêche la langue d'obstruer le pharynx.", cat: "conduite", diff: "moyen" },
      { q: "Que signifie un 'gasp' chez une victime inconsciente ?", a: ["Une respiration tout à fait normale", "Un réflexe agonique : à traiter comme une absence de respiration, signe d'arrêt cardiaque", "Un simple ronflement", "Une crise d'asthme"], c: 1, e: "Le gasp est un mouvement respiratoire réflexe inefficace, à ne pas confondre avec une respiration normale.", cat: "erreurs", diff: "difficile" },
      { q: "Combien de temps maximum doit durer l'examen de la respiration d'une victime inconsciente ?", a: ["5 secondes", "10 secondes maximum", "30 secondes", "1 minute"], c: 1, e: "10 secondes suffisent ; au-delà, on retarderait inutilement la réanimation en cas d'absence de respiration.", cat: "conduite", diff: "facile" },
      { q: "Une victime inconsciente qui respire doit-elle être surveillée jusqu'à l'arrivée des secours ?", a: ["Non, on peut la laisser seule", "Oui, surveillance continue de la conscience et de la respiration", "Seulement les 5 premières minutes", "Non, ce n'est pas nécessaire en PLS"], c: 1, e: "L'état d'une victime inconsciente peut évoluer rapidement (vomissement, arrêt respiratoire) : surveillance continue obligatoire.", cat: "gravite", diff: "moyen" },
      { q: "Mise en situation : une victime au sol ne répond pas à l'appel mais respire normalement. Quels sont les gestes dans l'ordre ?", a: ["Alerter, puis masser le cœur", "Libérer les voies aériennes, vérifier la respiration, mettre en PLS, alerter, surveiller", "La réveiller en la secouant fort", "L'asseoir immédiatement"], c: 1, e: "Ordre logique : bascule de la tête / libération des voies, contrôle de la respiration, PLS, alerte, surveillance continue.", cat: "pratique", diff: "moyen" },
      { q: "Faut-il donner à boire à une victime inconsciente ?", a: ["Oui, pour la réhydrater", "Non, jamais : risque d'étouffement (fausse route)", "Seulement de l'eau tiède", "Oui, en petite quantité"], c: 1, e: "Une victime inconsciente ne peut pas protéger ses voies aériennes : lui donner à boire expose à une fausse route grave.", cat: "erreurs", diff: "facile" }
    ]
  },
  {
    key: "arret_cardiaque",
    name: "L'arrêt cardiaque",
    icon: "🫀",
    questions: [
      { q: "Quel est le rythme recommandé pour le massage cardiaque chez l'adulte ?", a: ["15 compressions pour 2 insufflations", "30 compressions pour 2 insufflations", "100 compressions en continu sans insufflation possible", "10 compressions pour 1 insufflation"], c: 1, e: "30 compressions pour 2 insufflations, cycle répété sans interruption jusqu'à l'arrivée des secours ou la récupération d'un DAE.", cat: "conduite", diff: "facile" },
      { q: "Où positionner les mains pour le massage cardiaque ?", a: ["Sur le ventre", "Au centre de la poitrine, sur le sternum", "Sur le côté gauche des côtes", "Sur la gorge"], c: 1, e: "Les mains, l'une sur l'autre, sont placées au centre du thorax, sur la moitié inférieure du sternum.", cat: "conduite", diff: "facile" },
      { q: "Quelle profondeur de compression chez l'adulte ?", a: ["1 à 2 cm", "5 à 6 cm", "Environ 10 cm", "Aucune profondeur nécessaire"], c: 1, e: "5 à 6 cm pour générer une circulation sanguine suffisante. Ne pas hésiter à appuyer fermement.", cat: "conduite", diff: "moyen" },
      { q: "Quelle vitesse de compression recommandée ?", a: ["60/min", "100 à 120 compressions/min", "150/min", "200/min"], c: 1, e: "100 à 120 compressions par minute — le tempo de 'Stayin' Alive' sert souvent de repère.", cat: "conduite", diff: "moyen" },
      { q: "Quand utiliser un défibrillateur automatisé externe (DAE) ?", a: ["Dès qu'il est disponible, le plus tôt possible", "Seulement après 10 minutes de massage", "Seulement si un médecin est présent", "Seulement si la victime respire encore"], c: 0, e: "Le DAE doit être utilisé dès qu'il est disponible, sans attendre.", cat: "conduite", diff: "facile" },
      { q: "Pendant l'analyse du rythme cardiaque par le DAE, le secouriste doit :", a: ["Continuer le massage sans interruption", "Ne plus toucher la victime", "Parler fort à la victime", "Débrancher les électrodes"], c: 1, e: "Pendant l'analyse, tout contact peut fausser le résultat : il faut s'écarter et ne toucher personne.", cat: "erreurs", diff: "moyen" },
      { q: "Comment reconnaître un arrêt cardiaque ?", a: ["La victime parle normalement", "Victime inconsciente, qui ne respire pas ou seulement par gasps", "La victime tousse beaucoup", "La victime a juste un peu de fièvre"], c: 1, e: "L'arrêt cardiaque se reconnaît par l'absence de conscience et l'absence de respiration normale (ou des gasps).", cat: "reconnaissance", diff: "facile" },
      { q: "Faut-il arrêter le massage cardiaque dès que la victime semble reprendre connaissance ?", a: ["Non, on continue de toute façon", "Oui, on arrête si elle montre des signes de réveil (mouvements, respiration normale, ouverture des yeux)", "Seulement après 30 minutes", "Jamais avant l'arrivée des secours, même si elle se réveille"], c: 1, e: "Si la victime reprend des signes de vie évidents (mouvements, respiration normale), on arrête le massage et on surveille.", cat: "conduite", diff: "difficile" },
      { q: "Mise en situation : un collègue s'effondre, ne répond pas et ne respire pas. Vous êtes deux. Que faites-vous ?", a: ["L'un masse pendant que l'autre va chercher un café", "L'un alerte et va chercher un DAE pendant que l'autre débute immédiatement le massage cardiaque", "Vous attendez tous les deux les secours sans agir", "Vous le mettez en PLS et attendez"], c: 1, e: "À deux, on se répartit les tâches : massage immédiat sans interruption + alerte et recherche du DAE en parallèle.", cat: "pratique", diff: "moyen" },
      { q: "Erreur fréquente lors du massage cardiaque : relâcher complètement la pression entre deux compressions.", a: ["C'est obligatoire de bien relâcher complètement pour permettre au thorax de se réexpanser", "Il ne faut jamais relâcher", "Cela n'a pas d'importance", "Il faut presser en continu sans relâcher"], c: 0, e: "Il faut laisser le thorax reprendre sa position initiale entre chaque compression pour une efficacité optimale du massage.", cat: "erreurs", diff: "difficile" }
    ]
  },
  {
    key: "malaise",
    name: "Le malaise",
    icon: "🤒",
    questions: [
      { q: "Une victime consciente présente un malaise simple, sans signe de gravité. Que privilégier ?", a: ["La mettre au repos dans la position où elle se sent le mieux", "La faire courir pour stimuler la circulation", "La secouer pour la 'réveiller'", "L'ignorer en attendant que cela passe"], c: 0, e: "On installe la victime au repos, dans la position la plus confortable, on la rassure et on surveille.", cat: "conduite", diff: "facile" },
      { q: "Une victime se plaint d'une douleur thoracique. Comment considérer ce signe ?", a: ["Comme un simple problème digestif", "Comme un possible problème cardiaque, à prendre très au sérieux", "Comme une conséquence du stress uniquement", "Comme un signe sans importance"], c: 1, e: "Toute douleur thoracique doit être considérée comme pouvant traduire un problème cardiaque grave.", cat: "gravite", diff: "facile" },
      { q: "Une victime présente une difficulté à parler associée à une déformation du visage. À quoi penser ?", a: ["À de la fatigue passagère", "À un accident vasculaire cérébral (AVC)", "À une réaction allergique bénigne", "À une simple grimace"], c: 1, e: "Ces signes sont classiques d'un AVC. C'est une urgence vitale : alerter immédiatement les secours.", cat: "reconnaissance", diff: "moyen" },
      { q: "Quels sont les signes d'alerte d'un AVC à connaître (méthode simple) ?", a: ["Visage (sourire asymétrique), Bras (faiblesse d'un côté), Parole (difficulté à parler) → Temps (alerter vite)", "Fièvre, toux, fatigue", "Douleur au genou et maux de tête", "Aucun signe particulier à connaître"], c: 0, e: "Visage / Bras / Parole / Temps (méthode VBPT/FAST) permet de reconnaître rapidement un AVC et d'alerter sans délai.", cat: "reconnaissance", diff: "moyen" },
      { q: "Un malaise chez une personne diabétique connue, qui devient pâle et tremblante : à quoi penser ?", a: ["À une simple fatigue", "À une possible hypoglycémie", "À une réaction allergique", "À un coup de chaleur"], c: 1, e: "Pâleur, tremblements, sueurs chez un diabétique évoquent une hypoglycémie, à signaler aux secours.", cat: "situation", diff: "difficile" },
      { q: "Faut-il donner à manger ou à boire systématiquement à une personne en malaise ?", a: ["Oui, toujours du sucre", "Non, pas systématiquement : cela dépend du type de malaise et de l'état de conscience", "Oui, de l'eau uniquement", "Oui, un médicament quelconque"], c: 1, e: "On ne donne rien à boire/manger sans certitude sur la cause du malaise et l'état de conscience de la victime.", cat: "erreurs", diff: "moyen" },
      { q: "Erreur fréquente face à un malaise : minimiser et laisser repartir la victime qui dit 'ça va, ce n'est rien'.", a: ["Bonne pratique, on respecte son avis", "Erreur : il faut poursuivre l'examen même si la victime minimise", "On peut la laisser repartir sans souci", "Cela dépend de son âge"], c: 1, e: "Une victime peut minimiser la gravité réelle de son état : le SST doit systématiquement poursuivre son examen.", cat: "erreurs", diff: "facile" },
      { q: "Mise en situation : un collègue se plaint soudain de vertiges, sueurs et palpitations en pleine réunion. Que faites-vous ?", a: ["L'installer au repos, l'interroger sur ses antécédents, surveiller et alerter si signe de gravité persiste", "Lui dire de continuer la réunion s'il le supporte", "L'envoyer seul aux toilettes se rafraîchir", "Ne rien faire, ça passe souvent"], c: 0, e: "On met la victime au repos, on l'interroge, on surveille l'évolution et on alerte sans délai en cas de signe de gravité.", cat: "pratique", diff: "moyen" },
      { q: "Une personne fait un malaise avec perte de connaissance brève puis récupère totalement. Faut-il quand même alerter ?", a: ["Non si elle est complètement réveillée", "Oui, un avis médical reste recommandé pour rechercher la cause du malaise", "Seulement si elle tombe une deuxième fois", "Non, jamais nécessaire"], c: 1, e: "Toute perte de connaissance, même brève et récupérée, justifie un avis médical pour en rechercher la cause.", cat: "gravite", diff: "moyen" }
    ]
  },
  {
    key: "electrisation",
    name: "L'électrisation",
    icon: "⚡",
    questions: [
      { q: "Avant d'approcher une victime électrisée, que faire en priorité ?", a: ["La toucher pour vérifier son état", "Couper le courant ou écarter la source électrique sans se mettre en danger", "L'arroser d'eau", "Lui parler fort"], c: 1, e: "On ne touche jamais une victime sous tension : on coupe le courant à la source ou on l'écarte avec un objet isolant, sans danger pour soi.", cat: "conduite", diff: "facile" },
      { q: "Une fois la victime dégagée du courant, que peut-on observer ?", a: ["Toujours rien de visible", "Brûlures possibles aux points d'entrée/sortie du courant, et troubles du rythme cardiaque", "Uniquement une rougeur passagère", "Une simple fatigue"], c: 1, e: "L'électrisation peut provoquer des brûlures internes invisibles et des troubles cardiaques : un examen complet est indispensable.", cat: "gravite", diff: "moyen" },
      { q: "Mise en situation : un technicien reste accroché à un câble sous tension dans un local industriel. Que faire ?", a: ["Le tirer immédiatement à mains nues", "Couper l'alimentation électrique générale ou utiliser un objet isolant pour l'écarter", "Verser de l'eau sur lui", "Attendre qu'il se libère seul"], c: 1, e: "On coupe l'alimentation électrique avant tout contact, ou on utilise un matériau isolant sec pour écarter la source sans se mettre soi-même en danger.", cat: "pratique", diff: "difficile" },
      { q: "Après une électrisation, la victime semble bien et n'a pas mal. Faut-il quand même alerter ?", a: ["Non, si elle se sent bien", "Oui, un avis médical est systématique en raison du risque cardiaque retardé", "Seulement si elle a une brûlure visible", "Seulement pour les hautes tensions"], c: 1, e: "Le risque de trouble du rythme cardiaque peut apparaître après coup : un avis médical est systématique après toute électrisation.", cat: "erreurs", diff: "moyen" }
    ]
  }
];

// Aide : retourne une copie mélangée et filtrée des questions d'un module
window.getSstThemeQuestions = function(themeKey, options) {
  options = options || {};
  const theme = window.SST_THEMES.find(function(t) { return t.key === themeKey; });
  if (!theme) return [];
  let pool = theme.questions.slice();
  if (options.difficulty && options.difficulty !== 'all') {
    pool = pool.filter(function(q) { return q.diff === options.difficulty; });
  }
  // Mélange (Fisher-Yates léger via sort aléatoire, cohérent avec le reste de l'appli)
  pool = pool.slice().sort(function() { return 0.5 - Math.random(); });
  const count = options.count && options.count > 0 ? options.count : pool.length;
  return pool.slice(0, Math.min(count, pool.length));
};
